{{ if .Values.certificate.create }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-certificate
  namespace: {{ .Release.Namespace | default }}
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  dnsNames:
  {{- .Values.certificate.dnsNames | toYaml | nindent 4 }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: {{ .Release.Name }}
{{ end }}
